image: centos:7

before_script:
  - NODE_VERSION="10.13.0"
  - GO_VERSION="1.11.1"
  - yum -y install tar curl make git gcc gcc-c++ zip
  - cd /usr/local
  - curl -L https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | tar Jxf - --strip-components=1
  - curl -L https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | tar zxf - --strip-components=1

build:
  script:
    - cd ${CI_PROJECT_DIR}
    - export PATH=/usr/local/go/bin:$PATH
    - export GOPATH=/go
    - pwd
    - make install-deps
    - make dist
    - tar zcvf resources-public.tar.gz ./resources/public
  artifacts:
    paths:
      - "resources-public.tar.gz"
      - "dist/*.zip"
