image: centos:7

before_script:
  - yum -y install tar curl make git gcc gcc-c++ zip
  - cd /usr/local
  - curl -L https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz | tar Jxf - --strip-components=1
  - curl -L https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz | tar zxf - --strip-components=1

build:
  script:
    - cd ${CI_PROJECT_DIR}
    - export PATH=/usr/local/go/bin:$PATH
    - export GOPATH=/go
    - pwd
    - make install-deps
    - make dist
    - tar zcvf resources-public.tar.gz ./resources/public
  artifacts:
    paths:
      - "resources-public.tar.gz"
      - "dist/*.zip"
