sudo: true
language: go
go: 1.6
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - NODE_VERSION=4.2.3
    # Docker trigger token.
    - secure: RL1Ku0ikl6GBlsri8WSMOnCDFjQsMg/nDFZguq/xr0cNNNc1uYeTMxxd7yqXtKj4hhzu1K5jR5VywvN8pLj6KprjnTtXhtrlziwGWm/UoyZVs4Clo6pExsMue8FYNxyk7uqh1/IHpUokEksK26XHv/nes44OZTFsRT4/BszPLhk=
    # Only do deploy stuff if building from this repo.
    - DEPLOY_REPO=jasonish/evebox
    # Only do deploy stuff if building from this branch.
    - DEPLOY_BRANCH=master
    # BINTRAY_API_KEY
    - secure: "l57DadGF9BMue8hCFnUWDk/wXuCBS30PLAYx+wRhq7YUdW1m3srXj7AdlPr4f5uO2dRXYh/sFXEt2eWB1XqNMS+4PSMnc0fS9EtqA8ff4iQo48ig8BvzB0nBXp8BTDTYvP0PHVGM36UcM1r6ndstcBhnSq9Z5EOMWDo0tbEYrpw="
before_install:
- nvm install 4.2.3
- nvm use 4.2.3
- npm -g install webpack
script:
- make install-deps
- make
- make release
after_success:
- rvm install 2.1.1
- rvm use 2.1.1
- gem install fpm
- sudo apt-get -y install rpm
- make deb
- make rpm
- .travis/deploy-packages.sh
- .travis/docker.sh
