sudo: false

env:
  global:
    - GOPATH=~/gopath
    - PATH=${GOPATH}/bin:$PATH
    - NODE_VERSION=8.9.3
    - RUBY_VERSION=2.1.1

matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
          - rpm
          - gcc-mingw-w64
    language: go
    go: 1.8
  - os: osx
    osx_image: xcode8.1
    language: go
    go: 1.8

before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install $NODE_VERSION
      nvm use $NODE_VERSION
  fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew unlink node || true
      brew unlink go || true
      brew unlink glide || true
      brew install node
      brew install go
      brew install glide
      brew link node
      brew link go
      brew link glide
  fi

script:
- |
  make install-deps
  WITH_SQLITE=1 make dist

  # On Linux, make a Windows release as well.
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    WITH_SQLITE=1 GOOS=windows CC=x86_64-w64-mingw32-gcc make dist
  fi

  # Copy just what we want to deploy to S3 into a deploy directory, as
  # the S3 deployment step will copy everything in the directory
  # pointed at.
  mkdir -p deploy
  cp dist/*.zip deploy/

  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    rvm install $RUBY_VERSION
    rvm use $RUBY_VERSION
    gem install fpm
    sudo apt-get -y install rpm
    make deb
    make rpm
    cp dist/*.deb deploy/
    cp dist/*.rpm deploy/
  fi

deploy:
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: master
    acl: public_read
    upload-dir: master
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: develop
    acl: public_read
    upload-dir: develop
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: release-staging
    acl: public_read
    upload-dir: release-staging
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: release
    acl: public_read
    upload-dir: release
