sudo: true
language: go
go: 1.5
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - NODE_VERSION=4.2.3
    - secure: RL1Ku0ikl6GBlsri8WSMOnCDFjQsMg/nDFZguq/xr0cNNNc1uYeTMxxd7yqXtKj4hhzu1K5jR5VywvN8pLj6KprjnTtXhtrlziwGWm/UoyZVs4Clo6pExsMue8FYNxyk7uqh1/IHpUokEksK26XHv/nes44OZTFsRT4/BszPLhk=
  matrix:
before_install:
- nvm install 4.2.3
- nvm use 4.2.3
- npm -g install webpack
- gem install fpm
install: 
script:
- make install-deps
- make
- make release
- make deb
deploy:
  - provider: bintray
    user: jasonish
    on:
      branch: master
      repo: jasonish/evebox
    file: ".bintray/tarball.json"
    key:
      secure: a9F7D8r4bo51tCZqK9anQk6dLZRzLHv10AV8PHLPxMwHtVdpO01j5r2Yesa/h91ax2RGJn+HQDxMnxfB0gYv+cFzuL/+y5CtH8WyeHFWbiLrKfgsmRHmpueu5PswAfxnv5N/v40WbyxbgVxaWMCf3NuR66rmk+vYmKkh0PwZB14=
  - provider: bintray
    user: jasonish
    on:
      branch: master
      repo: jasonish/evebox
    file: ".bintray/debian.json"
    key:
      secure: a9F7D8r4bo51tCZqK9anQk6dLZRzLHv10AV8PHLPxMwHtVdpO01j5r2Yesa/h91ax2RGJn+HQDxMnxfB0gYv+cFzuL/+y5CtH8WyeHFWbiLrKfgsmRHmpueu5PswAfxnv5N/v40WbyxbgVxaWMCf3NuR66rmk+vYmKkh0PwZB14=
after_deploy:
- ./.travis/docker.sh
