platform: x64

os: Visual Studio 2013

build: off

test: off

branches:
  only:
    - develop
    - master

clone_folder: c:\gopath\src\github.com\jasonish\evebox

environment:
  GOPATH: c:\gopath
  BASH: \cygwin\bin\bash.exe

install:
  - \cygwin\setup-x86.exe -qnNdO -R C:/cygwin
      -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup
      -P make -P curl -P unzip -P zip
  - ps: Install-Product node LTS
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./.appveyor/build.sh"'

artifacts:
  - path: evebox.exe
  - path: dist/*

cache:
  - webapp\node_modules -> webapp\npm-shrinkwrap.json
  - windows-amd64/glide.exe
