version: '2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.5
    volumes:
      - /var/log/suricata:/var/log/suricata
      - ./etc/logstash/conf.d:/etc/logstash/conf.d
    command: /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/suricata.conf
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
