version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.3
    volumes:
      - ${LOGDIR:-/var/log/suricata}:/var/log/suricata
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
