version: "2"

services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
  suricata:
    build: ./suricata
    privileged: true
    network_mode: host
    environment:
      - INTERFACE
  evebox:
    image: jasonish/evebox:master
    volumes_from:
      - suricata
    links:
      - elasticsearch
    ports:
      - 5636:5636
    command: --input /var/log/suricata/eve.json -vv -e http://elasticsearch:9200
